import type { Project } from './types';

export const MOCK_PROJECTS: Project[] = [
  {
    id: 'mock-1',
    name: 'Document Processing Pipeline',
    description: 'Automated document ingestion and classification system using machine learning to route incoming correspondence to the correct team. Processes scanned PDFs, emails and physical mail digitised through departmental scanners.',
    projectStage: 'pilot',
    governanceTier: 'tier_2',
    createdAt: '2025-11-15T10:00:00Z',
    updatedAt: '2026-05-10T14:30:00Z',
    group: { id: 'g1', name: 'Digital Services' },
    directorate: { id: 'd1', name: 'Technology & Innovation' },
    businessAreas: [{ id: 'ba1', name: 'Correspondence Unit' }, { id: 'ba2', name: 'Records Management' }],
    capability: 'Document Processing',
    owner: { id: 'p1', name: 'Sarah Chen', email: 's.chen@gov.uk' },
    businessLead: { id: 'p2', name: 'James Morton', email: 'j.morton@gov.uk' },
    deliveryOwners: [{ id: 'p3', name: 'Priya Patel', email: 'p.patel@gov.uk' }],
    riskRegister: 'yes',
    dpiaInPlace: 'yes',
    actsInPlace: 'in_progress',
    ethicsFramework: 'yes',
    governanceBody: 'yes',
    governanceBodyName: 'Digital Board',
    supplier: 'In-house',
    activeUsers: '150',
    linkedActions: [{ id: 'a1', actionNo: '2.1', name: 'Automate manual processing workflows' }],
    updates: [
      { id: 'u1', heading: 'Pilot launch', content: 'Successfully launched pilot with 3 teams processing 500 documents/day. Accuracy rate at 94%. Minor issues with handwritten annotations being misclassified — training additional model variants.', timestamp: '2026-05-10T14:30:00Z' },
      { id: 'u2', heading: 'Model training complete', content: 'Completed training on 50k labelled documents. Performance benchmarks exceeded targets across all 7 document categories.', timestamp: '2026-04-22T09:00:00Z' },
      { id: 'u3', heading: 'Data pipeline established', content: 'Connected to central document store. Ingestion rate stable at 2000 docs/hour with 99.7% uptime over test period.', timestamp: '2026-03-15T11:00:00Z' },
    ],
  },
  {
    id: 'mock-2',
    name: 'Staff Scheduling Optimiser',
    description: 'Predictive scheduling tool that forecasts demand and optimises staff rosters across regional offices to reduce overtime costs and improve coverage during peak periods.',
    projectStage: 'scale',
    governanceTier: 'tier_1',
    createdAt: '2025-06-01T08:00:00Z',
    updatedAt: '2026-05-08T11:00:00Z',
    group: { id: 'g2', name: 'Operations' },
    directorate: { id: 'd2', name: 'Workforce Planning' },
    capability: 'Predictive Analytics',
    owner: { id: 'p4', name: 'Tom Davies', email: 't.davies@gov.uk' },
    businessLead: { id: 'p5', name: 'Maria Santos', email: 'm.santos@gov.uk' },
    riskRegister: 'yes',
    dpiaInPlace: 'yes',
    actsInPlace: 'yes',
    ethicsFramework: 'yes',
    governanceBody: 'yes',
    governanceBodyName: 'Ops Board',
    activeUsers: '2,400',
    linkedActions: [{ id: 'a2', actionNo: '1.3', name: 'Optimise workforce allocation' }],
    updates: [
      { id: 'u4', heading: 'National rollout complete', content: 'All 42 regional offices now live. Overtime costs reduced by 18% in Q1 2026. Staff satisfaction scores up 12 points.', timestamp: '2026-05-08T11:00:00Z' },
      { id: 'u5', heading: 'Phase 2 regions onboarded', content: '28 additional offices completed migration. Training delivered to 890 line managers.', timestamp: '2026-03-20T09:00:00Z' },
    ],
  },
  {
    id: 'mock-3',
    name: 'Citizen Feedback Portal',
    description: 'Online portal for citizens to submit feedback on public services, with sentiment analysis and automated routing to service teams. Includes multilingual support and accessibility features.',
    projectStage: 'idea',
    governanceTier: 'to_be_completed',
    createdAt: '2026-05-01T09:00:00Z',
    updatedAt: '2026-05-01T09:00:00Z',
    group: { id: 'g3', name: 'Policy' },
    directorate: { id: 'd3', name: 'Public Engagement' },
    capability: 'Public Facing',
    owner: { id: 'p6', name: 'Emma Richards', email: 'e.richards@gov.uk' },
    riskRegister: 'no',
    dpiaInPlace: 'not_sure',
    actsInPlace: 'no',
    ethicsFramework: 'no',
    governanceBody: 'no',
    updates: [],
  },
  {
    id: 'mock-4',
    name: 'Case Management Modernisation',
    description: 'Replacing legacy case management system with a cloud-native platform. Includes workflow automation, real-time reporting dashboards, and integration with 6 existing systems.',
    projectStage: 'scan',
    governanceTier: 'tier_3',
    createdAt: '2026-02-10T10:00:00Z',
    updatedAt: '2026-04-28T16:00:00Z',
    group: { id: 'g1', name: 'Digital Services' },
    directorate: { id: 'd4', name: 'Courts & Tribunals' },
    businessAreas: [{ id: 'ba3', name: 'Criminal Justice' }, { id: 'ba4', name: 'Family Court' }],
    capability: 'Case Management',
    owner: { id: 'p7', name: 'Michael Osei', email: 'm.osei@gov.uk' },
    businessLead: { id: 'p8', name: 'Helen Park', email: 'h.park@gov.uk' },
    legalLead: { id: 'p9', name: 'David Keane', email: 'd.keane@gov.uk' },
    riskRegister: 'yes',
    dpiaInPlace: 'in_progress',
    actsInPlace: 'no',
    ethicsFramework: 'not_sure',
    governanceBody: 'yes',
    governanceBodyName: 'Modernisation Board',
    supplier: 'Acme Corp',
    fundingSource: 'Central Digital Fund',
    linkedActions: [{ id: 'a3', actionNo: '3.2', name: 'Modernise legacy systems' }, { id: 'a4', actionNo: '1.1', name: 'Establish data foundations' }],
    updates: [
      { id: 'u6', heading: 'Vendor selected', content: 'Completed procurement. Acme Corp appointed as delivery partner. Kick-off scheduled for May. Contract value within approved budget envelope.', timestamp: '2026-04-28T16:00:00Z' },
      { id: 'u7', heading: 'Discovery complete', content: 'Mapped 47 existing workflows across 3 jurisdictions. Identified 12 quick wins for automation and 4 critical integration points.', timestamp: '2026-03-15T10:00:00Z' },
    ],
  },
  {
    id: 'mock-5',
    name: 'FOI Request Tracker',
    description: 'Internal tool to track and manage Freedom of Information requests with automated deadline monitoring, escalation workflows, and reporting to Information Commissioner\'s Office.',
    projectStage: 'stalled',
    governanceTier: 'tier_1',
    createdAt: '2025-09-01T08:00:00Z',
    updatedAt: '2026-03-01T10:00:00Z',
    group: { id: 'g3', name: 'Policy' },
    directorate: { id: 'd5', name: 'Legal & Compliance' },
    capability: 'Process Automation',
    owner: { id: 'p10', name: 'Lucy Brennan', email: 'l.brennan@gov.uk' },
    riskRegister: 'yes',
    dpiaInPlace: 'yes',
    actsInPlace: 'na',
    ethicsFramework: 'na',
    governanceBody: 'no',
    updates: [
      { id: 'u8', heading: 'Project paused', content: 'Development paused due to team reallocation to higher-priority compliance work. Will resume Q3 2026. Existing functionality stable for current users.', timestamp: '2026-03-01T10:00:00Z' },
    ],
  },
  {
    id: 'mock-6',
    name: 'Energy Efficiency Reporting',
    description: 'Dashboard for tracking energy consumption across government buildings with automated reporting to meet sustainability targets and Net Zero commitments.',
    projectStage: 'sunset',
    governanceTier: 'tier_1',
    createdAt: '2024-01-15T08:00:00Z',
    updatedAt: '2026-04-01T12:00:00Z',
    group: { id: 'g2', name: 'Operations' },
    directorate: { id: 'd6', name: 'Estates & Facilities' },
    capability: 'Reporting & Analytics',
    owner: { id: 'p11', name: 'Raj Kapoor', email: 'r.kapoor@gov.uk' },
    riskRegister: 'na',
    dpiaInPlace: 'na',
    actsInPlace: 'na',
    ethicsFramework: 'na',
    governanceBody: 'no',
    updates: [
      { id: 'u9', heading: 'Decommissioning planned', content: 'Being replaced by the cross-government Net Zero Dashboard. Migration of 3 years of historical data underway. Target decommission date: August 2026.', timestamp: '2026-04-01T12:00:00Z' },
    ],
  },
  {
    id: 'mock-7',
    name: 'Benefits Eligibility Calculator',
    description: 'Rules engine and citizen-facing calculator to help determine benefits eligibility across 14 schemes. Reduces call centre volume by enabling self-service.',
    projectStage: 'scale',
    governanceTier: 'tier_2',
    createdAt: '2025-04-10T08:00:00Z',
    updatedAt: '2026-05-12T09:00:00Z',
    group: { id: 'g3', name: 'Policy' },
    directorate: { id: 'd7', name: 'Benefits & Payments' },
    capability: 'Public Facing',
    owner: { id: 'p12', name: 'Aisha Khan', email: 'a.khan@gov.uk' },
    businessLead: { id: 'p13', name: 'Robert Ellis', email: 'r.ellis@gov.uk' },
    riskRegister: 'yes',
    dpiaInPlace: 'no',
    actsInPlace: 'yes',
    ethicsFramework: 'yes',
    governanceBody: 'yes',
    governanceBodyName: 'Benefits Oversight Committee',
    activeUsers: '45,000',
    linkedActions: [{ id: 'a5', actionNo: '2.3', name: 'Expand digital self-service' }],
    updates: [
      { id: 'u10', heading: 'Q1 performance review', content: 'Calculator handled 1.2M sessions in Q1. Call centre volume down 22%. Accessibility audit passed with minor findings being addressed.', timestamp: '2026-05-12T09:00:00Z' },
    ],
  },
  {
    id: 'mock-8',
    name: 'Internal Knowledge Base',
    description: 'Searchable knowledge management platform with semantic search, automated content tagging, and integration with existing SharePoint libraries.',
    projectStage: 'pilot',
    governanceTier: 'tier_1',
    createdAt: '2026-01-20T10:00:00Z',
    updatedAt: '2026-05-05T15:00:00Z',
    group: { id: 'g1', name: 'Digital Services' },
    directorate: { id: 'd1', name: 'Technology & Innovation' },
    capability: 'Search & Knowledge Management',
    owner: { id: 'p14', name: 'Chris Taylor', email: 'c.taylor@gov.uk' },
    riskRegister: 'no',
    dpiaInPlace: 'in_progress',
    actsInPlace: 'no',
    ethicsFramework: 'not_sure',
    governanceBody: 'no',
    supplier: 'In-house',
    activeUsers: '80',
    updates: [
      { id: 'u11', heading: 'Beta launch with pilot group', content: 'Launched beta with 80 users across 2 teams. Initial feedback positive — search relevance rated 4.2/5. Working on SharePoint connector stability.', timestamp: '2026-05-05T15:00:00Z' },
    ],
  },
  {
    id: 'mock-9',
    name: 'Fraud Detection Engine',
    description: 'Machine learning system to identify potentially fraudulent claims in real-time. Uses anomaly detection and pattern matching across historical datasets spanning 5 years.',
    projectStage: 'scan',
    governanceTier: 'tier_3',
    createdAt: '2026-03-01T08:00:00Z',
    updatedAt: '2026-05-14T10:00:00Z',
    group: { id: 'g2', name: 'Operations' },
    directorate: { id: 'd8', name: 'Counter-Fraud' },
    capability: 'Predictive Analytics',
    owner: { id: 'p15', name: 'Sandra Williams', email: 's.williams@gov.uk' },
    legalLead: { id: 'p16', name: 'Mark Thompson', email: 'm.thompson@gov.uk' },
    riskRegister: 'yes',
    dpiaInPlace: 'in_progress',
    actsInPlace: 'in_progress',
    ethicsFramework: 'yes',
    governanceBody: 'yes',
    governanceBodyName: 'Counter-Fraud Assurance Board',
    fundingSource: 'Counter-Fraud Programme',
    linkedActions: [{ id: 'a6', actionNo: '3.1', name: 'Strengthen fraud prevention' }],
    updates: [
      { id: 'u12', heading: 'Ethical review passed', content: 'Ethics board approved approach with conditions. Key condition: human review required for all flagged cases before action. Bias testing framework agreed.', timestamp: '2026-05-14T10:00:00Z' },
      { id: 'u13', heading: 'Data access agreed', content: 'MOU signed with data controller for access to anonymised historical claims data. Data ingestion pipeline being built.', timestamp: '2026-04-10T14:00:00Z' },
    ],
  },
  {
    id: 'mock-10',
    name: 'Translation Service',
    description: 'Real-time translation service for customer-facing communications supporting 12 languages. Deployed as a shared API consumed by 4 digital services.',
    projectStage: 'pilot',
    governanceTier: 'tier_2',
    createdAt: '2025-10-01T10:00:00Z',
    updatedAt: '2026-04-18T13:00:00Z',
    group: { id: 'g1', name: 'Digital Services' },
    directorate: { id: 'd3', name: 'Public Engagement' },
    businessAreas: [{ id: 'ba5', name: 'Customer Services' }],
    capability: 'Speech / Audio Processing',
    owner: { id: 'p17', name: 'Fatima Al-Rashid', email: 'f.alrashid@gov.uk' },
    riskRegister: 'yes',
    dpiaInPlace: 'yes',
    actsInPlace: 'yes',
    ethicsFramework: 'yes',
    governanceBody: 'yes',
    governanceBodyName: 'Digital Board',
    supplier: 'CloudTranslate Ltd',
    activeUsers: '320',
    updates: [
      { id: 'u14', heading: 'Accuracy benchmarks', content: 'BLEU scores: French 0.92, Polish 0.87, Urdu 0.81. Welsh support added ahead of schedule. Working on Arabic dialect handling.', timestamp: '2026-04-18T13:00:00Z' },
    ],
  },
];
