import type { Project } from './types';

export const MOCK_PROJECTS: Project[] = [
  {
    id: 'mock-1',
    name: 'Document Processing Pipeline',
    description: 'Automated document ingestion and classification system using machine learning to route incoming correspondence to the correct team.',
    projectStage: 'pilot',
    governanceTier: 'tier_2',
    createdAt: '2025-11-15T10:00:00Z',
    updatedAt: '2026-05-10T14:30:00Z',
    group: { id: 'g1', name: 'Digital Services' },
    directorate: { id: 'd1', name: 'Technology & Innovation' },
    capability: 'Document Processing',
    owner: { id: 'p1', name: 'Sarah Chen', email: 's.chen@gov.uk' },
    businessLead: { id: 'p2', name: 'James Morton', email: 'j.morton@gov.uk' },
    deliveryOwners: [{ id: 'p3', name: 'Priya Patel', email: 'p.patel@gov.uk' }],
    riskRegister: 'yes',
    dpiaInPlace: 'yes',
    actsInPlace: 'in_progress',
    ethicsFramework: 'yes',
    governanceBody: 'yes',
    governanceBodyName: 'Digital Board',
    supplier: 'In-house',
    activeUsers: '150',
    updates: [
      { id: 'u1', heading: 'Pilot launch', content: 'Successfully launched pilot with 3 teams processing 500 documents/day. Accuracy rate at 94%.', timestamp: '2026-05-10T14:30:00Z' },
      { id: 'u2', heading: 'Model training complete', content: 'Completed training on 50k labelled documents. Performance benchmarks exceeded targets.', timestamp: '2026-04-22T09:00:00Z' },
    ],
  },
  {
    id: 'mock-2',
    name: 'Staff Scheduling Optimiser',
    description: 'Predictive scheduling tool that forecasts demand and optimises staff rosters across regional offices to reduce overtime costs.',
    projectStage: 'scale',
    governanceTier: 'tier_1',
    createdAt: '2025-06-01T08:00:00Z',
    updatedAt: '2026-05-08T11:00:00Z',
    group: { id: 'g2', name: 'Operations' },
    directorate: { id: 'd2', name: 'Workforce Planning' },
    capability: 'Predictive Analytics',
    owner: { id: 'p4', name: 'Tom Davies', email: 't.davies@gov.uk' },
    riskRegister: 'yes',
    dpiaInPlace: 'yes',
    actsInPlace: 'yes',
    ethicsFramework: 'yes',
    governanceBody: 'yes',
    governanceBodyName: 'Ops Board',
    activeUsers: '2,400',
    updates: [
      { id: 'u3', heading: 'National rollout complete', content: 'All 42 regional offices now live. Overtime costs reduced by 18% in Q1 2026.', timestamp: '2026-05-08T11:00:00Z' },
    ],
  },
  {
    id: 'mock-3',
    name: 'Citizen Feedback Portal',
    description: 'Online portal for citizens to submit feedback on public services, with sentiment analysis and automated routing to service teams.',
    projectStage: 'idea',
    governanceTier: 'to_be_completed',
    createdAt: '2026-05-01T09:00:00Z',
    updatedAt: '2026-05-01T09:00:00Z',
    group: { id: 'g3', name: 'Policy' },
    directorate: { id: 'd3', name: 'Public Engagement' },
    capability: 'Public Facing',
    owner: { id: 'p5', name: 'Emma Richards', email: 'e.richards@gov.uk' },
    riskRegister: 'no',
    dpiaInPlace: 'not_sure',
    actsInPlace: 'no',
    ethicsFramework: 'no',
    governanceBody: 'no',
    updates: [],
  },
  {
    id: 'mock-4',
    name: 'Case Management Modernisation',
    description: 'Replacing legacy case management system with a cloud-native platform. Includes workflow automation and real-time reporting dashboards.',
    projectStage: 'scan',
    governanceTier: 'tier_3',
    createdAt: '2026-02-10T10:00:00Z',
    updatedAt: '2026-04-28T16:00:00Z',
    group: { id: 'g1', name: 'Digital Services' },
    directorate: { id: 'd4', name: 'Courts & Tribunals' },
    businessAreas: [{ id: 'ba1', name: 'Criminal Justice' }, { id: 'ba2', name: 'Family Court' }],
    capability: 'Case Management',
    owner: { id: 'p6', name: 'Michael Osei', email: 'm.osei@gov.uk' },
    businessLead: { id: 'p7', name: 'Helen Park', email: 'h.park@gov.uk' },
    legalLead: { id: 'p8', name: 'David Keane', email: 'd.keane@gov.uk' },
    riskRegister: 'yes',
    dpiaInPlace: 'in_progress',
    actsInPlace: 'no',
    ethicsFramework: 'not_sure',
    governanceBody: 'yes',
    governanceBodyName: 'Modernisation Board',
    supplier: 'Acme Corp',
    fundingSource: 'Central Digital Fund',
    updates: [
      { id: 'u4', heading: 'Vendor selected', content: 'Completed procurement. Acme Corp appointed as delivery partner. Kick-off scheduled for May.', timestamp: '2026-04-28T16:00:00Z' },
      { id: 'u5', heading: 'Discovery complete', content: 'Mapped 47 existing workflows across 3 jurisdictions. Identified 12 quick wins for automation.', timestamp: '2026-03-15T10:00:00Z' },
    ],
  },
  {
    id: 'mock-5',
    name: 'FOI Request Tracker',
    description: 'Internal tool to track and manage Freedom of Information requests with automated deadline monitoring and escalation.',
    projectStage: 'stalled',
    governanceTier: 'tier_1',
    createdAt: '2025-09-01T08:00:00Z',
    updatedAt: '2026-03-01T10:00:00Z',
    group: { id: 'g3', name: 'Policy' },
    directorate: { id: 'd5', name: 'Legal & Compliance' },
    capability: 'Process Automation',
    owner: { id: 'p9', name: 'Lucy Brennan', email: 'l.brennan@gov.uk' },
    riskRegister: 'yes',
    dpiaInPlace: 'yes',
    actsInPlace: 'na',
    ethicsFramework: 'na',
    governanceBody: 'no',
    updates: [
      { id: 'u6', heading: 'Project paused', content: 'Development paused due to team reallocation to higher-priority compliance work. Will resume Q3 2026.', timestamp: '2026-03-01T10:00:00Z' },
    ],
  },
  {
    id: 'mock-6',
    name: 'Energy Efficiency Reporting',
    description: 'Dashboard for tracking energy consumption across government buildings with automated reporting to meet sustainability targets.',
    projectStage: 'sunset',
    governanceTier: 'tier_1',
    createdAt: '2024-01-15T08:00:00Z',
    updatedAt: '2026-04-01T12:00:00Z',
    group: { id: 'g2', name: 'Operations' },
    directorate: { id: 'd6', name: 'Estates & Facilities' },
    capability: 'Reporting & Analytics',
    owner: { id: 'p10', name: 'Raj Kapoor', email: 'r.kapoor@gov.uk' },
    riskRegister: 'na',
    dpiaInPlace: 'na',
    actsInPlace: 'na',
    ethicsFramework: 'na',
    governanceBody: 'no',
    updates: [
      { id: 'u7', heading: 'Decommissioning planned', content: 'Being replaced by the cross-government Net Zero Dashboard. Migration of historical data underway.', timestamp: '2026-04-01T12:00:00Z' },
    ],
  },
];
